[build]
  command = "npm run build"
  publish = "build"

# SPAのルーティング設定（重要！）
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# PRプレビューの設定
[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"
